---
- name: Menjalankan bash script di managed node
  hosts: managed
  become: yes

  tasks:
    - name: Mengubah/menambahkan proxy ke repository
      ansible.builtin.lineinfile:
        path: /etc/yum.conf
        regexp: '^proxy='
        line: proxy=http://10.9.1.23:8080
        state: present

    - name: salin script ke remote 
      ansible.builtin.copy: 
        src: cekstatus.sh
        dest: /tmp/cekstatus.sh
        mode: '0755'

    - name: menjalankan script yang sudah di copy
      ansible.builtin.shell: /tmp/cekstatus.sh
